### ISSUE TITLE
ipywidgets.Image + voila

### ISSUE THREAD

**Issue by pllim** [voila-gallery/voila-gallery.github.io#29]
Hello. I have a hard time finding a working example using viola and `ipywidgets.Image`. Is it even possible? Thanks!

**Comment by martinRenou** [comment]
Hello. 

This should work perfectly. Can you share the code you tried and the error messages you encountered?

**Comment by pllim** [comment]
Yes, it does work, but I just couldn't find an example. Never mind.

**Comment by martinRenou** [comment]
Ah, sorry I misunderstood your question :)

**Comment by pllim** [comment]
But I was really trying to make it work with some existing custom widget that also has `Image`. I finally got it to work with `--enable_nbextensions=True`. 😸

**Comment by martinRenou** [comment]
Indeed. `--enable_nbextensions=True` will pick-up the extensions you installed locally (like the nbextension for ipywidgets). By default this is set to `False`, and voila will try to download the nbextension from npmjs, this doesn't work if you don't have access to the network.
